### PR TITLE
Automation Updates

### PR DESCRIPTION
**Pull request by cabutlermit**
### What does this PR do?

* Add Terraform-generated content to the Makefile to allow the developer to easily build and push containers to the Dev1 ECR repository from the local CLI
* Create the dev-build workflow (from the Terraform output) for automated container builds & uploads to Dev1 on pushes to any feature branch
* Create the stage-build workflow (from the Terraform output) for automated container builds & uploads to Stage-Workloads on any merges to the main branch
* Create the prod-promote workflow (from the Terraform output) for automated container uploads to Prod-Workloads on any tagged releases on the main branch

### Helpful background context

The ECR infrastructure for this application has already been deployed. The outputs from that Terraform run are provided here for the Makefile and the three GitHub Action workflows for automating the container publishing process to our AWS Organization.

### How can a reviewer manually see the effects of these changes?

The developer can use the new `make dist-dev` and `make publish-dev` from the local cli to verify that the container can be built and pushed to the ECR repository in Dev1. 

Testing of the automated workflows is difficult until they are merged to the `main` branch. They will run automatically, but cannot be triggered manually until they exist in `main`.

### Includes new or updated dependencies?

NO

### What are the relevant tickets?

* [IN-656](https://mitlibraries.atlassian.net/browse/IN-656)
* [IN-657](https://mitlibraries.atlassian.net/browse/IN-657)

### Developer

- [X] All new ENV is documented in README (or there is none)
- [X] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [x] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

[IN-656]: https://mitlibraries.atlassian.net/browse/IN-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cabutlermit** [comment]
@adamshire123 Let me know if you have any questions about the PR. And, if you want to pull in Eric or Helen to help with the review, go for it!

**Comment by adamshire123** [comment]
@ehanson8 I don't really know what I need to check here - can you give me some suggestions?

**Comment by cabutlermit** [comment]
@adamshire123 

Things to check: switch to this feature branch on your machine and 
1) run `make dist-dev` to see if the container build works correctly,
2) run `make publish-dev` to see if the container uploads to the ECR repository in Dev1 correctly
(You will need to be authenticated to AWS in your local CLI session -- there is more than one way to do this, but I find that the easiest way is to copy/paste the credentials from the "Commmand line or programmatic access" link on the SSO landing page https://mitlib.awsapps.com/start#/).

When I opened the PR, it did run the dev-build workflow (it's triggered on any pull request against the `main` branch), so you can look in the Actions tab in GitHub to see the run and see if it completed successfully.

**Comment by adamshire123** [comment]
Looks good @cabutlermit

**Review by adamshire123 — APPROVED** [review]
Looks good to me.

**Pull request merged**
